### ISSUE TITLE
bug: intermittent `packet commitment not found`

### ISSUE THREAD

**Issue by itsdevbear** [strangelove-ventures/ibctest#341]
Intermittently experiencing when running a very basic transfer test. Occurs maybe once every 5-10 runs or so. 

Can attach more logs. Running ask 0.46.4 and IBC v5 on the `berachain` side `osmosis v12.2.0` on the other.

Figured it might be a docker networking issue, has anyone experienced this before? 

```
logger.go:130: 2022-11-06T08:31:05.860Z	INFO	About to start container	{"image": "ghcr.io/cosmos/relayer:v2.1.2", "test_name": "TestIBCTestSuite/TestIBCTransfer", "command": "rly tx relay-pkts osmosis-berachain channel-0 --home /var/relayer-rly", "hostname": "TestIBCTestSuite_TestIBCTransfer-usnubd", "container": "TestIBCTestSuite_TestIBCTransfer-usnubd"}
99
    ibc_transfer_test.go:65: 
100
        	Error Trace:	/home/runner/work/berachain-node/berachain-node/tests/e2e/ibc/ibc_transfer_test.go:65
101
        	Error:      	Received unexpected error:
102
        	            	exit code 1:  ts=2022-11-06T08:31:06.233542Z lvl=info msg="Failed to relay packet from sequence" src_chain_id=osmosis-2 src_channel_id=channel-0 src_port_id=transfer dst_chain_id=berachain_420-1 dst_channel_id=channel-0 dst_port_id=transfer channel_order=ORDER_UNORDERED error="packet commitment not found"
103
        	            	Error: packet commitment not found
104
        	Test:       	TestIBCTestSuite/TestIBCTransfer
105
    setup.go:144: Container logs - {/berachain_420-1-val-1-TestIBCTestSuite_TestIBCTransfer}
106
```

**Comment by agouin** [comment]
Hi @itsdevbear , are you using the `FlushPackets` and `FlushAcknowledgements` methods to relay the packet?

https://github.com/strangelove-ventures/ibctest/blob/9942cb1a4f190c247bec5dda0b17bcbedb4dfdd6/examples/learn_ibc_test.go#L103-L104

I would suggest to start the relayer on the path using `StartRelayer` in the test case instead of using the manual flush methods, as this is how the relayer is used in production. It is also more reliable:

https://github.com/strangelove-ventures/ibctest/blob/9af4ad0fcdaf3480456872ab503661e6d8d58f72/examples/ibc/packet_forward_test.go#L128-L138

**Comment by agouin** [comment]
closing as stale
