### ISSUE TITLE
Periodically run tests for unstable chains. 

### ISSUE THREAD

**Issue by DavidNix** [strangelove-ventures/ibctest#80]
# Problem

Chains beyond our control (like Penumbra) tend to block PRs when the tests fail. In turn, this causes toil because the failure is not related to the PR changes. 

But we still want automated tests for these chains. 

PRs, typically, should have stable tests in order to protect developer speed. 

## Options

* Run periodically (once per day)?
* (Fancier) Only run unstable chain tests on certain file changes? 
* How to be alerted if upstream fails?

**Comment by agouin** [comment]
Had a good conversation with the penumbra team about this today. They said they had an issue that caused tags to be recreated, but it's resolved now. So using the specific penumbra tags like we're doing should be reliable moving forward.

Once we have the matrix files running against latest versions and have those tests running on a frequency outside of CI for reporting, this test will probably no longer be necessary. But I think right now while they are building out their ibc integration, it does help catch issues. I like the options you suggested, but until then I'd rather have the test run in CI instead of not at all.

The penumbra specific issue will be resolved in #78.

**Comment by DavidNix** [comment]
Understood and thanks for working it through with them. 

However, I'm still nervous about a potentially unstable dependency blocking PRs. 

Moreover, introducing non-cosmos chains is important but it's a huge prolbem unto itself that I feel requires a bit more strategy.

**Comment by jackzampolin** [comment]
We can start marking `t.Flaky` and things right?

**Comment by DavidNix** [comment]
> We can start marking t.Flaky and things right?

Ha, unfortunately, this one was consistently failing for a while, so even a "flaky" designation wouldn't have worked. 

I will try extending https://github.com/strangelove-ventures/ibctest/pull/79 to only penumbra and other chain tests if we modify those chain specific files. I think GH actions offer that flexibility (but I could be wrong there.)

**Comment by boojamya** [comment]
Currently have better concurrency. Potentially not necessary. Will re-open if needed.
